#ifndef CPRINTF_VULN_DEMO_H
#define CPRINTF_VULN_DEMO_H

#include "AEEStdDef.h"

#include "AEEInterface.h"

#if !defined(AEEINTERFACE_CPLUSPLUS)

#include "AEEStdDef.h"

//WARNING: This classID was locally generated by the wizard 6/19/2025
//For commercializing this module, please get a valid ClassID.
#define AEECLSID_CPRINTF_VULN_DEMO 0x00FE298

#else /* C++ */

#include "AEEStdDef.h"

//WARNING: This classID was locally generated by the wizard 6/19/2025
//For commercializing this module, please get a valid ClassID.
const AEECLSID AEECLSID_CPRINTF_VULN_DEMO = 0x00FE298;

#endif /* !defined(AEEINTERFACE_CPLUSPLUS) */

#endif /* #ifndef CPRINTF_VULN_DEMO_H */
